# subset players to only fantasy relevant positions
FF_POSITIONS = ['QB', 'RB', 'WR', 'TE', 'K']

SCHEDULES_COLUMNS = ["game_id", "season", "week", "home_team", "away_team", "home_score", "away_score", 
                     "home_rest", "away_rest", "roof", "surface", "temp", "wind"]

PLAYER_GAMES_COLUMNS = [
    "player_id",
    "game_id",
    "season",
    "week",
    "team",
    "opponent_team",
    "position", 
    
    # Passing
    "completions",
    "attempts",
    "passing_yards",
    "passing_tds",
    "passing_interceptions",
    "sacks_suffered",
    "sack_fumbles",
    "sack_fumbles_lost",
    "passing_air_yards",
    "passing_yards_after_catch",
    "passing_first_downs",
    "passing_epa",
    "passing_cpoe",
    "passing_2pt_conversions",
    "pacr",
    "passing_10",
    "passing_16",
    "passing_20",
    "passing_40",

    # Rushing
    "carries",
    "rushing_yards",
    "rushing_tds",
    "rushing_fumbles",
    "rushing_fumbles_lost",
    "rushing_first_downs",
    "rushing_epa",
    "rushing_2pt_conversions",
    "rushing_10",
    "rushing_12",
    "rushing_20",
    "rushing_40",

    # Receiving
    "receptions",
    "targets",
    "receiving_yards",
    "receiving_tds",
    "receiving_fumbles",
    "receiving_fumbles_lost",
    "receiving_air_yards",
    "receiving_yards_after_catch",
    "receiving_first_downs",
    "receiving_epa",
    "receiving_2pt_conversions",
    "receiving_10",
    "receiving_16",
    "receiving_20",
    "receiving_40",
    "racr",
    "target_share",
    "air_yards_share",
    "wopr",

    # Kicking
    'fg_att',
    'fg_blocked',
    'fg_blocked_distance',
    'fg_blocked_list',
    'fg_long',
    'fg_made',
    'fg_made_0_19',
    'fg_made_20_29',
    'fg_made_30_39',
    'fg_made_40_49',
    'fg_made_50_59',
    'fg_made_60_',
    'fg_made_distance',
    'fg_made_list',
    'fg_missed',
    'fg_missed_0_19',
    'fg_missed_20_29',
    'fg_missed_30_39',
    'fg_missed_40_49',
    'fg_missed_50_59',
    'fg_missed_60_',
    'fg_missed_distance',
    'fg_missed_list',
    'fg_pct',
    'pat_att',
    'pat_blocked',
    'pat_made',
    'pat_missed',
    'pat_pct',

    # Snaps
    "offense_snaps",
    "offense_pct",
    "offense_pct_total",
    "offense_pct_denom",
    "defense_snaps",
    "defense_pct",
    "st_snaps",
    "st_pct",

    # Next Gen rates/averages
    'passing_aggressiveness',
    'passing_aggressiveness_total',
    'passing_aggressiveness_denom',
    'passing_avg_air_distance',
    'passing_avg_air_distance_total',
    'passing_avg_air_distance_denom',
    'passing_avg_air_yards_differential',
    'passing_avg_air_yards_to_sticks',
    'passing_avg_air_yards_to_sticks_total',
    'passing_avg_air_yards_to_sticks_denom',
    'passing_avg_completed_air_yards',
    'passing_avg_completed_air_yards_total',
    'passing_avg_completed_air_yards_denom',
    'passing_avg_time_to_throw',
    'passing_avg_time_to_throw_total',
    'passing_avg_time_to_throw_denom',
    'passing_completion_percentage',
    'passing_completion_percentage_above_expectation',
    'passing_completion_percentage_above_expectation_total',
    'passing_completion_percentage_above_expectation_denom',
    'passing_expected_completion_percentage',
    'passing_expected_completion_percentage_total',
    'passing_expected_completion_percentage_denom',
    'passing_max_air_distance',
    'passing_max_completed_air_distance',
    'passing_passer_rating',
    'passing_avg_intended_air_yards',
    'passing_avg_intended_air_yards_total',
    'passing_avg_intended_air_yards_denom',
    'rushing_avg_rush_yards',
    'rushing_avg_rush_yards_total',
    'rushing_avg_rush_yards_denom',
    'rushing_avg_time_to_los',
    'rushing_avg_time_to_los_total',
    'rushing_avg_time_to_los_denom',
    'rushing_efficiency',
    'rushing_efficiency_total',
    'rushing_efficiency_denom',
    'rushing_expected_rush_yards',
    'rushing_percent_attempts_gte_eight_defenders',
    'rushing_percent_attempts_gte_eight_defenders_total',
    'rushing_percent_attempts_gte_eight_defenders_denom',
    'rushing_rush_pct_over_expected',
    'rushing_rush_pct_over_expected_total',
    'rushing_rush_pct_over_expected_denom',
    'rushing_rush_yards_over_expected',
    'rushing_rush_yards_over_expected_per_att',
    'receiving_avg_cushion',
    'receiving_avg_cushion_total',
    'receiving_avg_cushion_denom',
    'receiving_avg_expected_yac',
    'receiving_avg_expected_yac_total',
    'receiving_avg_expected_yac_denom',
    'receiving_avg_separation',
    'receiving_avg_separation_total',
    'receiving_avg_separation_denom',
    'receiving_avg_yac',
    'receiving_avg_yac_total',
    'receiving_avg_yac_denom',
    'receiving_avg_yac_above_expectation',
    'receiving_avg_yac_above_expectation_total',
    'receiving_avg_yac_above_expectation_denom',
    'receiving_catch_percentage',
    'receiving_catch_percentage_total',
    'receiving_catch_percentage_denom',
    'receiving_percent_share_of_intended_air_yards',
    'receiving_percent_share_of_intended_air_yards_total',
    'receiving_percent_share_of_intended_air_yards_denom',
    'receiving_avg_intended_air_yards',
    'receiving_avg_intended_air_yards_total',
    'receiving_avg_intended_air_yards_denom'
]

TEAM_GAMES_COLUMNS = [
    'game_id',
    'season',
    'week',
    'team',
    'opponent_team',

    # Passing
    'completions',
    'attempts',
    'passing_yards',
    'passing_tds',
    'passing_interceptions',
    'sacks_suffered',
    'sack_fumbles',
    'sack_fumbles_lost',
    'passing_air_yards',
    'passing_yards_after_catch',
    'passing_first_downs',
    'passing_epa',
    'passing_cpoe',
    'passing_2pt_conversions',
    'passing_10',
    'passing_16',
    'passing_20',
    'passing_40',

    # Rushing
    'carries',
    'rushing_yards',
    'rushing_tds',
    'rushing_fumbles',
    'rushing_fumbles_lost',
    'rushing_first_downs',
    'rushing_epa',
    'rushing_2pt_conversions',
    'rushing_10',
    'rushing_12',
    'rushing_20',
    'rushing_40',

    # Receiving
    'receptions',
    'targets',
    'receiving_yards',
    'receiving_tds',
    'receiving_fumbles',
    'receiving_fumbles_lost',
    'receiving_air_yards',
    'receiving_yards_after_catch',
    'receiving_first_downs',
    'receiving_epa',
    'receiving_2pt_conversions',
    'receiving_10',
    'receiving_16',
    'receiving_20',
    'receiving_40',

    # Defense/Special Teams
    'special_teams_tds',
    'def_tackles_for_loss',
    'def_fumbles_forced',
    'def_sacks',
    'def_qb_hits',
    'def_interceptions',
    'def_pass_defended',
    'def_tds',
    'def_fumbles',
    'def_safeties',
    'def_punt_blocks',
    'def_pat_blocks',
    'def_fg_blocks',
    'def_2pt_made',
    'def_three_and_outs',
    'def_fourth_down_stops',
    'def_yards_allowed',
    'def_points_allowed',
    'fumble_recovery_opp',
    'fumble_recovery_tds',
    'pt_return_tds'
 ]
