import Player from "../models/Player.js";

async function pushPlayer(player) {
    try {
        let p = await Player.findOne({
            name: player.name,
            position: player.position,
        });
        if (p) {
            p.team = player.team;
            if (!p.stats.some((stat) => stat.season === player.stats[0].season)) {
                p.stats.push(player.stats[0]);
            } else {
                p.stats = p.stats.map((s) =>
                    s.season !== player.stats[0].season ? s : player.stats[0]
                );
            }
            if (player.yearsOfExperience) {
                p.yearsOfExperience = player.yearsOfExperience;
            }
        } else {
            p = new Player(player);
        }
        return p.save();
    } catch (e) {
        console.log(e.message);
    }
}

const QB_MAPPING = {
    depthChart: 0,
    games: 1,
    gamesRank: 71,
    gamesPAR: 72,
    injuryCorrectionConstant: 31,
    injuryCorrectionConstantRank: 131,
    injuryCorrectionConstantPAR: 132,
    rushing: {
        attempts: 16,
        attemptsRank: 101,
        attemptsPAR: 102,
        attemptsMean: 17,
        attemptsMeanRank: 103,
        attemptsMeanPAR: 104,
        yards: 18,
        yardsRank: 105,
        yardsPAR: 106,
        yardsMean: 19,
        yardsMeanRank: 107,
        yardsMeanPAR: 108,
        yardsPerAttempt: 20,
        yardsPerAttemptRank: 109,
        yardsPerAttemptPAR: 110,
        firstDowns: 21,
        firstDownsRank: 111,
        firstDownsPAR: 112,
        firstDownsMean: 22,
        firstDownsMeanRank: 113,
        firstDownsMeanPAR: 114,
        td: 23,
        tdRank: 115,
        tdPAR: 116,
        tdMean: 24,
        tdMeanRank: 117,
        tdMeanPAR: 118,
    },
    passing: {
        completions: 2,
        completionsRank: 73,
        completionsPAR: 74,
        completionsMean: 3,
        completionsMeanRank: 75,
        completionsMeanPAR: 76,
        attempts: 4,
        attemptsRank: 77,
        attemptsPAR: 78,
        attemptsMean: 5,
        attemptsMeanRank: 79,
        attemptsMeanPAR: 80,
        percentage: 6,
        percentageRank: 81,
        percentagePAR: 82,
        yards: 7,
        yardsRank: 83,
        yardsPAR: 84,
        yardsMean: 8,
        yardsMeanRank: 85,
        yardsMeanPAR: 86,
        yardsPerAttempt: 9,
        yardsPerAttemptRank: 87,
        yardsPerAttemptPAR: 88,
        td: 10,
        tdRank: 89,
        tdPAR: 90,
        tdMean: 11,
        tdMeanRank: 91,
        tdMeanPAR: 92,
        interceptions: 12,
        interceptionsRank: 93,
        interceptionsPAR: 94,
        interceptionsMean: 13,
        interceptionsMeanRank: 95,
        interceptionsMeanPAR: 96,
        sacks: 14,
        sacksRank: 97,
        sacksPAR: 98,
        sacksMean: 15,
        sacksMeanRank: 99,
        sacksMeanPAR: 100,
    },
    misc: {
        opportunities: 27,
        opportunitiesRank: 123,
        opportunitiesPAR: 124,
        opportunitiesMean: 28,
        opportunitiesMeanRank: 125,
        opportunitiesMeanPAR: 126,
        firstDowns: 29,
        firstDownsRank: 127,
        firstDownsPAR: 128,
        firstDownsMean: 30,
        firstDownsMeanRank: 129,
        firstDownsMeanPAR: 130,
        fumblesLost: 25,
        fumblesLostRank: 119,
        fumblesLostPAR: 120,
        fumblesLostMean: 26,
        fumblesLostMeanRank: 121,
        fumblesLostMeanPAR: 122,
    },
    standard: {
        points: {
            sum: 32,
            sumRank: 133,
            sumPAR: 134,
            mean: 33,
            meanRank: 135,
            meanPAR: 136,
            median: 34,
            medianRank: 137,
            medianPAR: 138,
            standardDeviation: 35,
            standardDeviationRank: 139,
            standardDeviationPAR: 140,
            adjustedMean: 36,
            adjustedMeanRank: 141,
            adjustedMeanPAR: 142,
        },
        games: {
            bad: 37,
            badRank: 143,
            badPAR: 144,
            poor: 38,
            poorRank: 145,
            poorPAR: 146,
            okay: 39,
            okayRank: 147,
            okayPAR: 148,
            good: 40,
            goodRank: 149,
            goodPAR: 150,
            great: 41,
            greatRank: 151,
            greatPAR: 152,
        },
        qualityStartRatio: 42,
        qualityStartRatioRank: 153,
        qualityStartRatioPAR: 154,
        goodStartRatio: 43,
        goodStartRatioRank: 155,
        goodStartRatioPAR: 156,
        score: 44,
        scoreRank: 157,
        scorePAR: 158,
    },
    half: {
        points: {
            sum: 45,
            sumRank: 159,
            sumPAR: 160,
            mean: 46,
            meanRank: 161,
            meanPAR: 162,
            median: 47,
            medianRank: 163,
            medianPAR: 164,
            standardDeviation: 48,
            standardDeviationRank: 165,
            standardDeviationPAR: 166,
            adjustedMean: 49,
            adjustedMeanRank: 167,
            adjustedMeanPAR: 168,
        },
        games: {
            bad: 50,
            badRank: 169,
            badPAR: 170,
            poor: 51,
            poorRank: 171,
            poorPAR: 172,
            okay: 52,
            okayRank: 173,
            okayPAR: 174,
            good: 53,
            goodRank: 175,
            goodPAR: 176,
            great: 54,
            greatRank: 177,
            greatPAR: 178,
        },
        qualityStartRatio: 55,
        qualityStartRatioRank: 179,
        qualityStartRatioPAR: 180,
        goodStartRatio: 56,
        goodStartRatioRank: 181,
        goodStartRatioPAR: 182,
        score: 57,
        scoreRank: 183,
        scorePAR: 184,
    },
    ppr: {
        points: {
            sum: 58,
            sumRank: 185,
            sumPAR: 186,
            mean: 59,
            meanRank: 187,
            meanPAR: 188,
            median: 60,
            medianRank: 189,
            medianPAR: 190,
            standardDeviation: 61,
            standardDeviationRank: 191,
            standardDeviationPAR: 192,
            adjustedMean: 62,
            adjustedMeanRank: 193,
            adjustedMeanPAR: 194,
        },
        games: {
            bad: 63,
            badRank: 195,
            badPAR: 196,
            poor: 64,
            poorRank: 197,
            poorPAR: 198,
            okay: 65,
            okayRank: 199,
            okayPAR: 200,
            good: 66,
            goodRank: 201,
            goodPAR: 202,
            great: 67,
            greatRank: 203,
            greatPAR: 204,
        },
        qualityStartRatio: 68,
        qualityStartRatioRank: 205,
        qualityStartRatioPAR: 206,
        goodStartRatio: 69,
        goodStartRatioRank: 207,
        goodStartRatioPAR: 208,
        score: 70,
        scoreRank: 209,
        scorePAR: 210,
    },
};

const RB_MAPPING = {
    depthChart: 0,
    games: 1,
    gamesRank: 75,
    gamesPAR: 76,
    injuryCorrectionConstant: 35,
    injuryCorrectionConstantRank: 143,
    injuryCorrectionConstantPAR: 144,
    rushing: {
        attempts: 2,
        attemptsRank: 77,
        attemptsPAR: 78,
        attemptsMean: 3,
        attemptsMeanRank: 79,
        attemptsMeanPAR: 80,
        yards: 4,
        yardsRank: 81,
        yardsPAR: 82,
        yardsMean: 5,
        yardsMeanRank: 83,
        yardsMeanPAR: 84,
        yardsPerAttempt: 6,
        yardsPerAttemptRank: 85,
        yardsPerAttemptPAR: 86,
        firstDowns: 7,
        firstDownsRank: 87,
        firstDownsPAR: 88,
        firstDownsMean: 8,
        firstDownsMeanRank: 89,
        firstDownsMeanPAR: 90,
        long: 9,
        longRank: 91,
        longPAR: 92,
        longMean: 10,
        longMeanRank: 93,
        longMeanPAR: 94,
        twentyPlus: 11,
        twentyPlusRank: 95,
        twentyPlusPAR: 96,
        twentyPlusMean: 12,
        twentyPlusMeanRank: 97,
        twentyPlusMeanPAR: 98,
        td: 13,
        tdRank: 99,
        tdPAR: 100,
        tdMean: 14,
        tdMeanRank: 101,
        tdMeanPAR: 102,
    },
    receiving: {
        receptions: 15,
        receptionsRank: 103,
        receptionsPAR: 104,
        receptionsMean: 16,
        receptionsMeanRank: 105,
        receptionsMeanPAR: 106,
        targets: 17,
        targetsRank: 107,
        targetsPAR: 108,
        targetsMean: 18,
        targetsMeanRank: 109,
        targetsMeanPAR: 110,
        yards: 19,
        yardsRank: 111,
        yardsPAR: 112,
        yardsMean: 20,
        yardsMeanRank: 113,
        yardsMeanPAR: 114,
        yardsPerReception: 21,
        yardsPerReceptionRank: 115,
        yardsPerReceptionPAR: 116,
        firstDowns: 22,
        firstDownsRank: 117,
        firstDownsPAR: 118,
        firstDownsMean: 23,
        firstDownsMeanRank: 119,
        firstDownsMeanPAR: 120,
        td: 24,
        tdRank: 121,
        tdPAR: 122,
        tdMean: 25,
        tdMeanRank: 123,
        tdMeanPAR: 124,
    },
    misc: {
        touches: 26,
        touchesRank: 125,
        touchesPAR: 126,
        touchesMean: 27,
        touchesMeanRank: 127,
        touchesMeanPAR: 128,
        opportunities: 28,
        opportunitiesRank: 129,
        opportunitiesPAR: 130,
        opportunitiesMean: 29,
        opportunitiesMeanRank: 131,
        opportunitiesMeanPAR: 132,
        firstDowns: 30,
        firstDownsRank: 133,
        firstDownsPAR: 134,
        firstDownsMean: 31,
        firstDownsMeanRank: 135,
        firstDownsMeanPAR: 136,
        fumblesLost: 32,
        fumblesLostRank: 137,
        fumblesLostPAR: 138,
        fumblesLostMean: 33,
        fumblesLostMeanRank: 139,
        fumblesLostMeanPAR: 140,
        fumblesLostPerTouch: 34,
        fumblesLostPerTouchRank: 141,
        fumblesLostPerTouchPAR: 142,
    },
    standard: {
        points: {
            sum: 36,
            sumRank: 145,
            sumPAR: 146,
            mean: 37,
            meanRank: 147,
            meanPAR: 148,
            median: 38,
            medianRank: 149,
            medianPAR: 150,
            standardDeviation: 39,
            standardDeviationRank: 151,
            standardDeviationPAR: 152,
            adjustedMean: 40,
            adjustedMeanRank: 153,
            adjustedMeanPAR: 154,
        },
        games: {
            bad: 41,
            badRank: 155,
            badPAR: 156,
            poor: 42,
            poorRank: 157,
            poorPAR: 158,
            okay: 43,
            okayRank: 159,
            okayPAR: 160,
            good: 44,
            goodRank: 161,
            goodPAR: 162,
            great: 45,
            greatRank: 163,
            greatPAR: 164,
        },
        qualityStartRatio: 46,
        qualityStartRatioRank: 165,
        qualityStartRatioPAR: 166,
        goodStartRatio: 47,
        goodStartRatioRank: 167,
        goodStartRatioPAR: 168,
        score: 48,
        scoreRank: 169,
        scorePAR: 170,
    },
    half: {
        points: {
            sum: 49,
            sumRank: 171,
            sumPAR: 172,
            mean: 50,
            meanRank: 173,
            meanPAR: 174,
            median: 51,
            medianRank: 175,
            medianPAR: 176,
            standardDeviation: 52,
            standardDeviationRank: 177,
            standardDeviationPAR: 178,
            adjustedMean: 53,
            adjustedMeanRank: 179,
            adjustedMeanPAR: 180,
        },
        games: {
            bad: 54,
            badRank: 181,
            badPAR: 182,
            poor: 55,
            poorRank: 183,
            poorPAR: 184,
            okay: 56,
            okayRank: 185,
            okayPAR: 186,
            good: 57,
            goodRank: 187,
            goodPAR: 188,
            great: 58,
            greatRank: 189,
            greatPAR: 190,
        },
        qualityStartRatio: 59,
        qualityStartRatioRank: 191,
        qualityStartRatioPAR: 192,
        goodStartRatio: 60,
        goodStartRatioRank: 193,
        goodStartRatioPAR: 194,
        score: 61,
        scoreRank: 195,
        scorePAR: 196,
    },
    ppr: {
        points: {
            sum: 62,
            sumRank: 197,
            sumPAR: 198,
            mean: 63,
            meanRank: 199,
            meanPAR: 200,
            median: 64,
            medianRank: 201,
            medianPAR: 202,
            standardDeviation: 65,
            standardDeviationRank: 203,
            standardDeviationPAR: 204,
            adjustedMean: 66,
            adjustedMeanRank: 205,
            adjustedMeanPAR: 206,
        },
        games: {
            bad: 67,
            badRank: 207,
            badPAR: 208,
            poor: 68,
            poorRank: 209,
            poorPAR: 210,
            okay: 69,
            okayRank: 211,
            okayPAR: 212,
            good: 70,
            goodRank: 213,
            goodPAR: 214,
            great: 71,
            greatRank: 215,
            greatPAR: 216,
        },
        qualityStartRatio: 72,
        qualityStartRatioRank: 217,
        qualityStartRatioPAR: 218,
        goodStartRatio: 73,
        goodStartRatioRank: 219,
        goodStartRatioPAR: 220,
        score: 74,
        scoreRank: 221,
        scorePAR: 222,
    },
};

//WRs and TEs (PC = PassCatcher)
const PC_MAPPING = {
    depthChart: 0,
    games: 1,
    gamesRank: 75,
    gamesPAR: 76,
    injuryCorrectionConstant: 35,
    injuryCorrectionConstantRank: 143,
    injuryCorrectionConstantPAR: 144,
    rushing: {
        attempts: 17,
        attemptsRank: 107,
        attemptsPAR: 108,
        attemptsMean: 18,
        attemptsMeanRank: 109,
        attemptsMeanPAR: 110,
        yards: 19,
        yardsRank: 111,
        yardsPAR: 112,
        yardsMean: 20,
        yardsMeanRank: 113,
        yardsMeanPAR: 114,
        yardsPerAttempt: 21,
        yardsPerAttemptRank: 115,
        yardsPerAttemptPAR: 116,
        firstDowns: 22,
        firstDownsRank: 117,
        firstDownsPAR: 118,
        firstDownsMean: 23,
        firstDownsMeanRank: 119,
        firstDownsMeanPAR: 120,
        td: 24,
        tdRank: 121,
        tdPAR: 122,
        tdMean: 25,
        tdMeanRank: 123,
        tdMeanPAR: 124,
    },
    receiving: {
        receptions: 2,
        receptionsRank: 77,
        receptionsPAR: 78,
        receptionsMean: 3,
        receptionsMeanRank: 79,
        receptionsMeanPAR: 80,
        targets: 4,
        targetsRank: 81,
        targetsPAR: 82,
        targetsMean: 5,
        targetsMeanRank: 83,
        targetsMeanPAR: 84,
        yards: 6,
        yardsRank: 85,
        yardsPAR: 86,
        yardsMean: 7,
        yardsMeanRank: 87,
        yardsMeanPAR: 88,
        yardsPerReception: 8,
        yardsPerReceptionRank: 89,
        yardsPerReceptionPAR: 90,
        firstDowns: 9,
        firstDownsRank: 91,
        firstDownsPAR: 92,
        firstDownsMean: 10,
        firstDownsMeanRank: 93,
        firstDownsMeanPAR: 94,
        long: 11,
        longRank: 95,
        longPAR: 96,
        longMean: 12,
        longMeanRank: 97,
        longMeanPAR: 98,
        twentyPlus: 13,
        twentyPlusRank: 99,
        twentyPlusPAR: 100,
        twentyPlusMean: 14,
        twentyPlusMeanRank: 101,
        twentyPlusMeanPAR: 102,
        td: 15,
        tdRank: 103,
        tdPAR: 104,
        tdMean: 16,
        tdMeanRank: 105,
        tdMeanPAR: 106,
    },
    misc: {
        touches: 26,
        touchesRank: 125,
        touchesPAR: 126,
        touchesMean: 27,
        touchesMeanRank: 127,
        touchesMeanPAR: 128,
        opportunities: 28,
        opportunitiesRank: 129,
        opportunitiesPAR: 130,
        opportunitiesMean: 29,
        opportunitiesMeanRank: 131,
        opportunitiesMeanPAR: 132,
        firstDowns: 30,
        firstDownsRank: 133,
        firstDownsPAR: 134,
        firstDownsMean: 31,
        firstDownsMeanRank: 135,
        firstDownsMeanPAR: 136,
        fumblesLost: 32,
        fumblesLostRank: 137,
        fumblesLostPAR: 138,
        fumblesLostMean: 33,
        fumblesLostMeanRank: 139,
        fumblesLostMeanPAR: 140,
        fumblesLostPerTouch: 34,
        fumblesLostPerTouchRank: 141,
        fumblesLostPerTouchPAR: 142,
    },
    standard: {
        points: {
            sum: 36,
            sumRank: 145,
            sumPAR: 146,
            mean: 37,
            meanRank: 147,
            meanPAR: 148,
            median: 38,
            medianRank: 149,
            medianPAR: 150,
            standardDeviation: 39,
            standardDeviationRank: 151,
            standardDeviationPAR: 152,
            adjustedMean: 40,
            adjustedMeanRank: 153,
            adjustedMeanPAR: 154,
        },
        games: {
            bad: 41,
            badRank: 155,
            badPAR: 156,
            poor: 42,
            poorRank: 157,
            poorPAR: 158,
            okay: 43,
            okayRank: 159,
            okayPAR: 160,
            good: 44,
            goodRank: 161,
            goodPAR: 162,
            great: 45,
            greatRank: 163,
            greatPAR: 164,
        },
        qualityStartRatio: 46,
        qualityStartRatioRank: 165,
        qualityStartRatioPAR: 166,
        goodStartRatio: 47,
        goodStartRatioRank: 167,
        goodStartRatioPAR: 168,
        score: 48,
        scoreRank: 169,
        scorePAR: 170,
    },
    half: {
        points: {
            sum: 49,
            sumRank: 171,
            sumPAR: 172,
            mean: 50,
            meanRank: 173,
            meanPAR: 174,
            median: 51,
            medianRank: 175,
            medianPAR: 176,
            standardDeviation: 52,
            standardDeviationRank: 177,
            standardDeviationPAR: 178,
            adjustedMean: 53,
            adjustedMeanRank: 179,
            adjustedMeanPAR: 180,
        },
        games: {
            bad: 54,
            badRank: 181,
            badPAR: 182,
            poor: 55,
            poorRank: 183,
            poorPAR: 184,
            okay: 56,
            okayRank: 185,
            okayPAR: 186,
            good: 57,
            goodRank: 187,
            goodPAR: 188,
            great: 58,
            greatRank: 189,
            greatPAR: 190,
        },
        qualityStartRatio: 59,
        qualityStartRatioRank: 191,
        qualityStartRatioPAR: 192,
        goodStartRatio: 60,
        goodStartRatioRank: 193,
        goodStartRatioPAR: 194,
        score: 61,
        scoreRank: 195,
        scorePAR: 196,
    },
    ppr: {
        points: {
            sum: 62,
            sumRank: 197,
            sumPAR: 198,
            mean: 63,
            meanRank: 199,
            meanPAR: 200,
            median: 64,
            medianRank: 201,
            medianPAR: 202,
            standardDeviation: 65,
            standardDeviationRank: 203,
            standardDeviationPAR: 204,
            adjustedMean: 66,
            adjustedMeanRank: 205,
            adjustedMeanPAR: 206,
        },
        games: {
            bad: 67,
            badRank: 207,
            badPAR: 208,
            poor: 68,
            poorRank: 209,
            poorPAR: 210,
            okay: 69,
            okayRank: 211,
            okayPAR: 212,
            good: 70,
            goodRank: 213,
            goodPAR: 214,
            great: 71,
            greatRank: 215,
            greatPAR: 216,
        },
        qualityStartRatio: 72,
        qualityStartRatioRank: 217,
        qualityStartRatioPAR: 218,
        goodStartRatio: 73,
        goodStartRatioRank: 219,
        goodStartRatioPAR: 220,
        score: 74,
        scoreRank: 221,
        scorePAR: 222,
    },
};

const K_MAPPING = {
    depthChart: 0,
    games: 1,
    gamesRank: 66,
    gamesPAR: 67,
    injuryCorrectionConstant: 26,
    injuryCorrectionConstantRank: 116,
    injuryCorrectionConstantPAR: 117,
    kicking: {
        fieldGoals: {
            sum: 2,
            sumRank: 68,
            sumPAR: 69,
            mean: 3,
            meanRank: 70,
            meanPAR: 71,
            attempts: 4,
            attemptsRank: 72,
            attemptsPAR: 73,
            attemptsMean: 5,
            attemptsMeanRank: 74,
            attemptsMeanPAR: 75,
            percentage: 6,
            percentageRank: 76,
            percentagePAR: 77,
            long: 7,
            longRank: 78,
            longPAR: 79,
            longMean: 8,
            longMeanRank: 80,
            longMeanPAR: 81,
            sum10_19: 9,
            sum10_19Rank: 82,
            sum10_19PAR: 83,
            mean10_19: 10,
            mean10_19Rank: 84,
            mean10_19PAR: 85,
            sum20_29: 11,
            sum20_29Rank: 86,
            sum20_29PAR: 87,
            mean20_29: 12,
            mean20_29Rank: 88,
            mean20_29PAR: 89,
            sum30_39: 13,
            sum30_39Rank: 90,
            sum30_39PAR: 91,
            mean30_39: 14,
            mean30_39Rank: 92,
            mean30_39PAR: 93,
            sum40_49: 15,
            sum40_49Rank: 94,
            sum40_49PAR: 95,
            mean40_49: 16,
            mean40_49Rank: 96,
            mean40_49PAR: 97,
            sum50Plus: 17,
            sum50PlusRank: 98,
            sum50PlusPAR: 99,
            mean50Plus: 18,
            mean50PlusRank: 100,
            mean50PlusPAR: 101,
        },
        extraPoints: {
            sum: 19,
            sumRank: 102,
            sumPAR: 103,
            mean: 20,
            meanRank: 104,
            meanPAR: 105,
            attempts: 21,
            attemptsRank: 106,
            attemptsPAR: 107,
            attemptsMean: 22,
            attemptsMeanRank: 108,
            attemptsMeanPAR: 109,
            percentage: 23,
            percentageRank: 110,
            percentagePAR: 111,
        },
    },
    misc: {
        opportunities: 24,
        opportunitiesRank: 112,
        opportunitiesPAR: 113,
        opportunitiesMean: 25,
        opportunitiesMeanRank: 114,
        opportunitiesMeanPAR: 115,
    },
    standard: {
        points: {
            sum: 27,
            sumRank: 118,
            sumPAR: 119,
            mean: 28,
            meanRank: 120,
            meanPAR: 121,
            median: 29,
            medianRank: 122,
            medianPAR: 123,
            standardDeviation: 30,
            standardDeviationRank: 124,
            standardDeviationPAR: 125,
            adjustedMean: 31,
            adjustedMeanRank: 126,
            adjustedMeanPAR: 127,
        },
        games: {
            bad: 32,
            badRank: 128,
            badPAR: 129,
            poor: 33,
            poorRank: 130,
            poorPAR: 131,
            okay: 34,
            okayRank: 132,
            okayPAR: 133,
            good: 35,
            goodRank: 134,
            goodPAR: 135,
            great: 36,
            greatRank: 136,
            greatPAR: 137,
        },
        qualityStartRatio: 37,
        qualityStartRatioRank: 138,
        qualityStartRatioPAR: 139,
        goodStartRatio: 38,
        goodStartRatioRank: 140,
        goodStartRatioPAR: 141,
        score: 39,
        scoreRank: 142,
        scorePAR: 143,
    },
    half: {
        points: {
            sum: 40,
            sumRank: 144,
            sumPAR: 145,
            mean: 41,
            meanRank: 146,
            meanPAR: 147,
            median: 42,
            medianRank: 148,
            medianPAR: 149,
            standardDeviation: 43,
            standardDeviationRank: 150,
            standardDeviationPAR: 151,
            adjustedMean: 44,
            adjustedMeanRank: 152,
            adjustedMeanPAR: 153,
        },
        games: {
            bad: 45,
            badRank: 154,
            badPAR: 155,
            poor: 46,
            poorRank: 156,
            poorPAR: 157,
            okay: 47,
            okayRank: 158,
            okayPAR: 159,
            good: 48,
            goodRank: 160,
            goodPAR: 161,
            great: 49,
            greatRank: 162,
            greatPAR: 163,
        },
        qualityStartRatio: 50,
        qualityStartRatioRank: 164,
        qualityStartRatioPAR: 165,
        goodStartRatio: 51,
        goodStartRatioRank: 166,
        goodStartRatioPAR: 167,
        score: 52,
        scoreRank: 168,
        scorePAR: 169,
    },
    ppr: {
        points: {
            sum: 53,
            sumRank: 170,
            sumPAR: 171,
            mean: 54,
            meanRank: 172,
            meanPAR: 173,
            median: 55,
            medianRank: 174,
            medianPAR: 175,
            standardDeviation: 56,
            standardDeviationRank: 176,
            standardDeviationPAR: 177,
            adjustedMean: 57,
            adjustedMeanRank: 178,
            adjustedMeanPAR: 179,
        },
        games: {
            bad: 58,
            badRank: 180,
            badPAR: 181,
            poor: 59,
            poorRank: 182,
            poorPAR: 183,
            okay: 60,
            okayRank: 184,
            okayPAR: 185,
            good: 61,
            goodRank: 186,
            goodPAR: 187,
            great: 62,
            greatRank: 188,
            greatPAR: 189,
        },
        qualityStartRatio: 63,
        qualityStartRatioRank: 190,
        qualityStartRatioPAR: 191,
        goodStartRatio: 64,
        goodStartRatioRank: 192,
        goodStartRatioPAR: 193,
        score: 65,
        scoreRank: 194,
        scorePAR: 195,
    },
};

const DST_MAPPING = {
    games: 0,
    dst: {
        defense: {
            sacks: 1,
            sacksRank: 54,
            sacksPAR: 55,
            sacksMean: 2,
            sacksMeanRank: 56,
            sacksMeanPAR: 57,
            interceptions: 3,
            interceptionsRank: 58,
            interceptionsPAR: 59,
            interceptionsMean: 4,
            interceptionsMeanRank: 60,
            interceptionsMeanPAR: 61,
            fumblesRecovered: 5,
            fumblesRecoveredRank: 62,
            fumblesRecoveredPAR: 63,
            fumblesRecoveredMean: 6,
            fumblesRecoveredMeanRank: 64,
            fumblesRecoveredMeanPAR: 65,
            forcedFumbles: 7,
            forcedFumblesRank: 66,
            forcedFumblesPAR: 67,
            forcedFumblesMean: 8,
            forcedFumblesMeanRank: 68,
            forcedFumblesMeanPAR: 69,
            safeties: 9,
            safetiesRank: 70,
            safetiesPAR: 71,
            safetiesMean: 10,
            safetiesMeanRank: 72,
            safetiesMeanPAR: 73,
            td: 11,
            tdRank: 74,
            tdPAR: 75,
            tdMean: 12,
            tdMeanRank: 76,
            tdMeanPAR: 77,
        },
        specialTeams: {
            td: 13,
            tdRank: 78,
            tdPAR: 79,
            tdMean: 14,
            tdMeanRank: 80,
            tdMeanPAR: 81,
        },
    },
    standard: {
        points: {
            sum: 15,
            sumRank: 82,
            sumPAR: 83,
            mean: 16,
            meanRank: 84,
            meanPAR: 85,
            median: 17,
            medianRank: 86,
            medianPAR: 87,
            standardDeviation: 18,
            standardDeviationRank: 88,
            standardDeviationPAR: 89,
            adjustedMean: 19,
            adjustedMeanRank: 90,
            adjustedMeanPAR: 91,
        },
        games: {
            bad: 20,
            badRank: 92,
            badPAR: 93,
            poor: 21,
            poorRank: 94,
            poorPAR: 95,
            okay: 22,
            okayRank: 96,
            okayPAR: 97,
            good: 23,
            goodRank: 98,
            goodPAR: 99,
            great: 24,
            greatRank: 100,
            greatPAR: 101,
        },
        qualityStartRatio: 25,
        qualityStartRatioRank: 102,
        qualityStartRatioPAR: 103,
        goodStartRatio: 26,
        goodStartRatioRank: 104,
        goodStartRatioPAR: 105,
        score: 27,
        scoreRank: 106,
        scorePAR: 107,
    },
    half: {
        points: {
            sum: 28,
            sumRank: 108,
            sumPAR: 109,
            mean: 29,
            meanRank: 110,
            meanPAR: 111,
            median: 30,
            medianRank: 112,
            medianPAR: 113,
            standardDeviation: 31,
            standardDeviationRank: 114,
            standardDeviationPAR: 115,
            adjustedMean: 32,
            adjustedMeanRank: 116,
            adjustedMeanPAR: 117,
        },
        games: {
            bad: 33,
            badRank: 118,
            badPAR: 119,
            poor: 34,
            poorRank: 120,
            poorPAR: 121,
            okay: 35,
            okayRank: 122,
            okayPAR: 123,
            good: 36,
            goodRank: 124,
            goodPAR: 125,
            great: 37,
            greatRank: 126,
            greatPAR: 127,
        },
        qualityStartRatio: 38,
        qualityStartRatioRank: 128,
        qualityStartRatioPAR: 129,
        goodStartRatio: 39,
        goodStartRatioRank: 130,
        goodStartRatioPAR: 131,
        score: 40,
        scoreRank: 132,
        scorePAR: 133,
    },
    ppr: {
        points: {
            sum: 41,
            sumRank: 134,
            sumPAR: 135,
            mean: 42,
            meanRank: 136,
            meanPAR: 137,
            median: 43,
            medianRank: 138,
            medianPAR: 139,
            standardDeviation: 44,
            standardDeviationRank: 140,
            standardDeviationPAR: 141,
            adjustedMean: 45,
            adjustedMeanRank: 142,
            adjustedMeanPAR: 143,
        },
        games: {
            bad: 46,
            badRank: 144,
            badPAR: 145,
            poor: 47,
            poorRank: 146,
            poorPAR: 147,
            okay: 48,
            okayRank: 148,
            okayPAR: 149,
            good: 49,
            goodRank: 150,
            goodPAR: 151,
            great: 50,
            greatRank: 152,
            greatPAR: 153,
        },
        qualityStartRatio: 51,
        qualityStartRatioRank: 154,
        qualityStartRatioPAR: 155,
        goodStartRatio: 52,
        goodStartRatioRank: 156,
        goodStartRatioPAR: 157,
        score: 53,
        scoreRank: 158,
        scorePAR: 159,
    },
};

function buildStats(mapping, numbers) {
    const stats = {};
    for (const key in mapping) {
        if (typeof mapping[key] === "number") {
            stats[key] = numbers[mapping[key]];
        } else if (typeof mapping[key] === "object") {
            stats[key] = buildStats(mapping[key], numbers);
        }
    }
    return stats;
}

function parsePlayer(row, filename, mapping) {
    const info = row.slice(0, 3);
    const numbers = row.slice(3).map(Number);
    let season = "Weighted Average";
    const year = /\d+/.exec(filename);
    if (year) season = year[0];
    const player = {
        name: info[0],
        team: info[1],
        position: info[2],
        stats: [
            {
                season,
                ...buildStats(mapping, numbers),
            },
        ],
    };
    if (filename.includes("all.csv")) {
        player.yearsOfExperience = numbers[numbers.length - 4];
        player.stats[0].half.projected = {
            mean: numbers[numbers.length - 3],
            sum: numbers[numbers.length - 2],
            rank: numbers[numbers.length - 1],
        };
    }
    return pushPlayer(player);
}

export const parseQB = (row, filename) => parsePlayer(row, filename, QB_MAPPING);
export const parseRB = (row, filename) => parsePlayer(row, filename, RB_MAPPING);
export const parsePC = (row, filename) => parsePlayer(row, filename, PC_MAPPING);
export const parseK = (row, filename) => parsePlayer(row, filename, K_MAPPING);
export const parseDST = (row, filename) => parsePlayer(row, filename, DST_MAPPING);